"""Render demo/config.js from the canonical prompt module.

The demo must send the EXACT system prompt the model was trained/evaluated
with, so config.js is generated, never hand-edited.

Usage:
    python demo/make_config.py --base-url https://<tunnel>.trycloudflare.com/v1
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))
from prompts.triage_prompt import SYSTEM_PROMPT  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", default="http://localhost:8000/v1")
    args = parser.parse_args()

    out = Path(__file__).parent / "config.js"
    out.write_text(
        "// GENERATED by demo/make_config.py — do not edit by hand.\n"
        f"window.VLLM_BASE_URL = {json.dumps(args.base_url)};\n"
        f"window.TRIAGE_SYSTEM_PROMPT = {json.dumps(SYSTEM_PROMPT)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {out} (base URL: {args.base_url})")


if __name__ == "__main__":
    main()
